// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "ntgraphctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CNtgraphctrl1

IMPLEMENT_DYNCREATE(CNtgraphctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNtgraphctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CNtgraphctrl1 operations
